### ISSUE TITLE
Unable to load IHC component

### ISSUE THREAD

**Issue by davidolrik** [dingusdk/haihc#6]
My config:
```
ihc:
  - url: 'http://192.168.1.2'
    username: secret
    password: secret
    auto_setup: true
    info: true
```

The error I get in the log:

```
2019-01-12 22:44:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component ihc
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/ihc/__init__.py", line 151, in setup
    if not ihc_setup(hass, config, controller_conf, index):
  File "/usr/src/app/homeassistant/components/ihc/__init__.py", line 172, in ihc_setup
    hass, config, ihc_controller, controller_id)):
  File "/usr/src/app/homeassistant/components/ihc/__init__.py", line 241, in autosetup_ihc_products
    component_setup, groups, controller_id)
  File "/usr/src/app/homeassistant/components/ihc/__init__.py", line 268, in get_discovery_info
    'note': product.attrib['note'],
KeyError: 'note'
```

**Comment by davidolrik** [comment]
It now works again as of 0.86.2
